export type IngredientItem = { id: string; name: string; emoji: string; cal: number; };
export type Category = { id: string; label: string; emoji: string; color: string; items: IngredientItem[]; };

export const CATEGORIES: Category[] = [
  { id: 'veggies', label: 'Veggies', emoji: '🥦', color: '#22c55e', items: [
    { id: 'v1', name: 'Broccoli', emoji: '🥦', cal: 55 }, { id: 'v2', name: 'Carrot', emoji: '🥕', cal: 41 },
    { id: 'v3', name: 'Tomato', emoji: '🍅', cal: 22 }, { id: 'v4', name: 'Spinach', emoji: '🌿', cal: 23 },
    { id: 'v5', name: 'Bell Pepper', emoji: '🫑', cal: 31 }, { id: 'v6', name: 'Mushroom', emoji: '🍄', cal: 22 },
    { id: 'v7', name: 'Corn', emoji: '🌽', cal: 86 }, { id: 'v8', name: 'Eggplant', emoji: '🍆', cal: 35 },
    { id: 'v9', name: 'Zucchini', emoji: '🥒', cal: 17 }, { id: 'v10', name: 'Onion', emoji: '🧅', cal: 40 },
    { id: 'v11', name: 'Potato', emoji: '🥔', cal: 77 }, { id: 'v12', name: 'Avocado', emoji: '🥑', cal: 160 },
    { id: 'v13', name: 'Sweet Potato', emoji: '🍠', cal: 86 }, { id: 'v14', name: 'Asparagus', emoji: '🎋', cal: 20 },
    { id: 'v15', name: 'Cabbage', emoji: '🥬', cal: 25 }, { id: 'v16', name: 'Kale', emoji: '🌱', cal: 35 },
    { id: 'v17', name: 'Cauliflower', emoji: '🥦', cal: 25 }, { id: 'v18', name: 'Brussels Sprout', emoji: '🟢', cal: 43 },
    { id: 'v19', name: 'Cucumber', emoji: '🥒', cal: 16 }, { id: 'v20', name: 'Leek', emoji: '🌿', cal: 31 },
    { id: 'v21', name: 'Celery', emoji: '🌿', cal: 14 }, { id: 'v22', name: 'Beetroot', emoji: '🔴', cal: 43 },
    { id: 'v23', name: 'Radish', emoji: '🔴', cal: 19 }, { id: 'v24', name: 'Peas', emoji: '🟢', cal: 62 },
    { id: 'v25', name: 'Green Beans', emoji: '🌿', cal: 31 }, { id: 'v26', name: 'Artichoke', emoji: '🟢', cal: 47 },
    { id: 'v27', name: 'Pumpkin', emoji: '🎃', cal: 26 }, { id: 'v28', name: 'Bok Choy', emoji: '🥬', cal: 13 },
  ]},
  { id: 'proteins', label: 'Proteins', emoji: '🥩', color: '#f97316', items: [
    { id: 'p1', name: 'Chicken', emoji: '🍗', cal: 239 }, { id: 'p2', name: 'Eggs', emoji: '🥚', cal: 78 },
    { id: 'p3', name: 'Salmon', emoji: '🐟', cal: 208 }, { id: 'p4', name: 'Tofu', emoji: '⬜', cal: 76 },
    { id: 'p5', name: 'Beef', emoji: '🥩', cal: 250 }, { id: 'p6', name: 'Shrimp', emoji: '🦐', cal: 84 },
    { id: 'p7', name: 'Pork', emoji: '🥓', cal: 242 }, { id: 'p8', name: 'Lentils', emoji: '🫘', cal: 116 },
    { id: 'p9', name: 'Chickpeas', emoji: '🥣', cal: 164 }, { id: 'p10', name: 'Turkey', emoji: '🦃', cal: 189 },
    { id: 'p11', name: 'Paneer', emoji: '🧀', cal: 265 }, { id: 'p12', name: 'Tuna', emoji: '🐟', cal: 132 },
    { id: 'p13', name: 'Sardines', emoji: '🐟', cal: 208 }, { id: 'p14', name: 'Lamb', emoji: '🐑', cal: 294 },
    { id: 'p15', name: 'Duck', emoji: '🦆', cal: 337 }, { id: 'p16', name: 'Crab', emoji: '🦀', cal: 97 },
    { id: 'p17', name: 'Lobster', emoji: '🦞', cal: 98 }, { id: 'p18', name: 'Scallops', emoji: '🐚', cal: 111 },
    { id: 'p19', name: 'Tempeh', emoji: '🫘', cal: 195 }, { id: 'p20', name: 'Edamame', emoji: '🟢', cal: 121 },
    { id: 'p21', name: 'Black Beans', emoji: '🫘', cal: 132 }, { id: 'p22', name: 'Greek Yogurt', emoji: '🥛', cal: 100 },
    { id: 'p23', name: 'Cottage Cheese', emoji: '🧀', cal: 98 }, { id: 'p24', name: 'Whey Protein', emoji: '💪', cal: 120 },
  ]},
  { id: 'pantry', label: 'Pantry', emoji: '🫙', color: '#a78bfa', items: [
    { id: 'pa1', name: 'Rice', emoji: '🍚', cal: 206 }, { id: 'pa2', name: 'Pasta', emoji: '🍝', cal: 220 },
    { id: 'pa3', name: 'Garlic', emoji: '🧄', cal: 4 }, { id: 'pa4', name: 'Olive Oil', emoji: '🫙', cal: 119 },
    { id: 'pa5', name: 'Lemon', emoji: '🍋', cal: 29 }, { id: 'pa6', name: 'Chili', emoji: '🌶️', cal: 18 },
    { id: 'pa7', name: 'Cheese', emoji: '🧀', cal: 113 }, { id: 'pa8', name: 'Butter', emoji: '🧈', cal: 102 },
    { id: 'pa9', name: 'Soy Sauce', emoji: '🧴', cal: 9 }, { id: 'pa10', name: 'Honey', emoji: '🍯', cal: 64 },
    { id: 'pa11', name: 'Flour', emoji: '🥡', cal: 364 }, { id: 'pa12', name: 'Milk', emoji: '🥛', cal: 42 },
    { id: 'pa13', name: 'Coconut Milk', emoji: '🥥', cal: 230 }, { id: 'pa14', name: 'Bread', emoji: '🍞', cal: 265 },
    { id: 'pa15', name: 'Ginger', emoji: '🫚', cal: 80 }, { id: 'pa16', name: 'Tomato Paste', emoji: '🥫', cal: 82 },
    { id: 'pa17', name: 'Vinegar', emoji: '🧴', cal: 3 }, { id: 'pa18', name: 'Mustard', emoji: '🟡', cal: 3 },
    { id: 'pa19', name: 'Oats', emoji: '🥣', cal: 307 }, { id: 'pa20', name: 'Breadcrumbs', emoji: '🍞', cal: 395 },
    { id: 'pa21', name: 'Cornstarch', emoji: '🫙', cal: 381 }, { id: 'pa22', name: 'Tahini', emoji: '🫙', cal: 89 },
    { id: 'pa23', name: 'Peanut Butter', emoji: '🥜', cal: 188 }, { id: 'pa24', name: 'Sesame Oil', emoji: '🫙', cal: 120 },
    { id: 'pa25', name: 'Fish Sauce', emoji: '🧴', cal: 6 }, { id: 'pa26', name: 'Worcestershire', emoji: '🧴', cal: 13 },
    { id: 'pa27', name: 'Sugar', emoji: '🍬', cal: 387 }, { id: 'pa28', name: 'Brown Sugar', emoji: '🟤', cal: 380 },
    { id: 'pa29', name: 'Baking Powder', emoji: '🫙', cal: 2 }, { id: 'pa30', name: 'Vegetable Broth', emoji: '🫙', cal: 12 },
  ]},
  { id: 'fruits', label: 'Fruits', emoji: '🍎', color: '#ec4899', items: [
    { id: 'f1', name: 'Apple', emoji: '🍎', cal: 95 }, { id: 'f2', name: 'Banana', emoji: '🍌', cal: 89 },
    { id: 'f3', name: 'Strawberry', emoji: '🍓', cal: 49 }, { id: 'f4', name: 'Blueberry', emoji: '🫐', cal: 57 },
    { id: 'f5', name: 'Mango', emoji: '🥭', cal: 99 }, { id: 'f6', name: 'Orange', emoji: '🍊', cal: 62 },
    { id: 'f7', name: 'Grapes', emoji: '🍇', cal: 62 }, { id: 'f8', name: 'Pineapple', emoji: '🍍', cal: 50 },
    { id: 'f9', name: 'Watermelon', emoji: '🍉', cal: 30 }, { id: 'f10', name: 'Peach', emoji: '🍑', cal: 59 },
    { id: 'f11', name: 'Pear', emoji: '🍐', cal: 57 }, { id: 'f12', name: 'Cherry', emoji: '🍒', cal: 50 },
    { id: 'f13', name: 'Kiwi', emoji: '🥝', cal: 42 }, { id: 'f14', name: 'Raspberry', emoji: '🍓', cal: 32 },
    { id: 'f15', name: 'Pomegranate', emoji: '🔴', cal: 83 }, { id: 'f16', name: 'Papaya', emoji: '🧡', cal: 43 },
    { id: 'f17', name: 'Lychee', emoji: '🔴', cal: 66 }, { id: 'f18', name: 'Coconut', emoji: '🥥', cal: 283 },
    { id: 'f19', name: 'Lime', emoji: '🍋', cal: 20 }, { id: 'f20', name: 'Fig', emoji: '🫐', cal: 74 },
  ]},
  { id: 'dairy', label: 'Dairy & Eggs', emoji: '🥛', color: '#60a5fa', items: [
    { id: 'd1', name: 'Whole Milk', emoji: '🥛', cal: 149 }, { id: 'd2', name: 'Skim Milk', emoji: '🥛', cal: 86 },
    { id: 'd3', name: 'Heavy Cream', emoji: '🥛', cal: 414 }, { id: 'd4', name: 'Sour Cream', emoji: '🥄', cal: 60 },
    { id: 'd5', name: 'Cream Cheese', emoji: '🧀', cal: 99 }, { id: 'd6', name: 'Cheddar', emoji: '🧀', cal: 113 },
    { id: 'd7', name: 'Mozzarella', emoji: '🧀', cal: 85 }, { id: 'd8', name: 'Parmesan', emoji: '🧀', cal: 111 },
    { id: 'd9', name: 'Feta', emoji: '🧀', cal: 75 }, { id: 'd10', name: 'Brie', emoji: '🧀', cal: 95 },
    { id: 'd11', name: 'Plain Yogurt', emoji: '🥣', cal: 61 }, { id: 'd12', name: 'Oat Milk', emoji: '🥛', cal: 120 },
    { id: 'd13', name: 'Almond Milk', emoji: '🥛', cal: 30 }, { id: 'd14', name: 'Soy Milk', emoji: '🥛', cal: 80 },
    { id: 'd15', name: 'Ghee', emoji: '🧈', cal: 130 }, { id: 'd16', name: 'Egg White', emoji: '🥚', cal: 17 },
    { id: 'd17', name: 'Egg Yolk', emoji: '🟡', cal: 55 }, { id: 'd18', name: 'Ricotta', emoji: '🧀', cal: 87 },
    { id: 'd19', name: 'Whipped Cream', emoji: '🍦', cal: 51 }, { id: 'd20', name: 'Condensed Milk', emoji: '🥛', cal: 123 },
  ]},
  { id: 'grains', label: 'Grains & Baked', emoji: '🌾', color: '#d97706', items: [
    { id: 'g1', name: 'White Rice', emoji: '🍚', cal: 206 }, { id: 'g2', name: 'Brown Rice', emoji: '🍚', cal: 216 },
    { id: 'g3', name: 'Quinoa', emoji: '🌾', cal: 222 }, { id: 'g4', name: 'Spaghetti', emoji: '🍝', cal: 220 },
    { id: 'g5', name: 'Penne', emoji: '🍝', cal: 220 }, { id: 'g6', name: 'Sourdough', emoji: '🍞', cal: 185 },
    { id: 'g7', name: 'Whole Wheat Bread', emoji: '🍞', cal: 128 }, { id: 'g8', name: 'Bagel', emoji: '🥯', cal: 245 },
    { id: 'g9', name: 'Croissant', emoji: '🥐', cal: 231 }, { id: 'g10', name: 'Tortilla', emoji: '🫓', cal: 146 },
    { id: 'g11', name: 'Naan', emoji: '🫓', cal: 262 }, { id: 'g12', name: 'Pita', emoji: '🫓', cal: 165 },
    { id: 'g13', name: 'Cornmeal', emoji: '🌽', cal: 442 }, { id: 'g14', name: 'Barley', emoji: '🌾', cal: 193 },
    { id: 'g15', name: 'Couscous', emoji: '🍚', cal: 176 }, { id: 'g16', name: 'Millet', emoji: '🌾', cal: 207 },
    { id: 'g17', name: 'Buckwheat', emoji: '🌾', cal: 155 }, { id: 'g18', name: 'Granola', emoji: '🥣', cal: 471 },
    { id: 'g19', name: 'Waffle', emoji: '🧇', cal: 218 }, { id: 'g20', name: 'Pancake', emoji: '🥞', cal: 175 },
  ]},
  { id: 'beverages', label: 'Beverages', emoji: '☕', color: '#14b8a6', items: [
    { id: 'b1', name: 'Water', emoji: '💧', cal: 0 }, { id: 'b2', name: 'Black Coffee', emoji: '☕', cal: 2 },
    { id: 'b3', name: 'Latte', emoji: '🥛', cal: 120 }, { id: 'b4', name: 'Espresso', emoji: '☕', cal: 5 },
    { id: 'b5', name: 'Green Tea', emoji: '🍵', cal: 2 }, { id: 'b6', name: 'Black Tea', emoji: '🍵', cal: 2 },
    { id: 'b7', name: 'Orange Juice', emoji: '🍊', cal: 112 }, { id: 'b8', name: 'Apple Juice', emoji: '🍎', cal: 114 },
    { id: 'b9', name: 'Smoothie', emoji: '🥤', cal: 150 }, { id: 'b10', name: 'Protein Shake', emoji: '💪', cal: 200 },
    { id: 'b11', name: 'Energy Drink', emoji: '⚡', cal: 110 }, { id: 'b12', name: 'Cola', emoji: '🥤', cal: 140 },
    { id: 'b13', name: 'Beer', emoji: '🍺', cal: 153 }, { id: 'b14', name: 'Red Wine', emoji: '🍷', cal: 125 },
    { id: 'b15', name: 'Sparkling Water', emoji: '💧', cal: 0 }, { id: 'b16', name: 'Kombucha', emoji: '🍵', cal: 30 },
    { id: 'b17', name: 'Coconut Water', emoji: '🥥', cal: 46 }, { id: 'b18', name: 'Chocolate Milk', emoji: '🥛', cal: 180 },
    { id: 'b19', name: 'Matcha Latte', emoji: '🍵', cal: 90 }, { id: 'b20', name: 'Oat Milk Coffee', emoji: '☕', cal: 100 },
  ]},
  { id: 'spices', label: 'Spices & Herbs', emoji: '🌿', color: '#84cc16', items: [
    { id: 's1', name: 'Salt', emoji: '🧂', cal: 0 }, { id: 's2', name: 'Black Pepper', emoji: '⚫', cal: 6 },
    { id: 's3', name: 'Cumin', emoji: '🟤', cal: 8 }, { id: 's4', name: 'Turmeric', emoji: '🟡', cal: 8 },
    { id: 's5', name: 'Paprika', emoji: '🔴', cal: 6 }, { id: 's6', name: 'Cinnamon', emoji: '🟤', cal: 6 },
    { id: 's7', name: 'Oregano', emoji: '🌿', cal: 5 }, { id: 's8', name: 'Thyme', emoji: '🌿', cal: 3 },
    { id: 's9', name: 'Rosemary', emoji: '🌿', cal: 3 }, { id: 's10', name: 'Basil', emoji: '🌿', cal: 1 },
    { id: 's11', name: 'Coriander', emoji: '🌿', cal: 5 }, { id: 's12', name: 'Cayenne', emoji: '🌶️', cal: 6 },
    { id: 's13', name: 'Garlic Powder', emoji: '🧄', cal: 9 }, { id: 's14', name: 'Onion Powder', emoji: '🧅', cal: 8 },
    { id: 's15', name: 'Bay Leaves', emoji: '🍃', cal: 2 }, { id: 's16', name: 'Cardamom', emoji: '🌿', cal: 6 },
    { id: 's17', name: 'Cloves', emoji: '🟤', cal: 7 }, { id: 's18', name: 'Nutmeg', emoji: '🟤', cal: 12 },
    { id: 's19', name: 'Vanilla Extract', emoji: '🫙', cal: 12 }, { id: 's20', name: 'Smoked Paprika', emoji: '🔴', cal: 6 },
    { id: 's21', name: "Za'atar", emoji: '🌿', cal: 8 }, { id: 's22', name: 'Curry Powder', emoji: '🟡', cal: 7 },
    { id: 's23', name: 'Garam Masala', emoji: '🟤', cal: 8 }, { id: 's24', name: 'Chili Flakes', emoji: '🌶️', cal: 6 },
    { id: 's25', name: 'Dill', emoji: '🌿', cal: 1 }, { id: 's26', name: 'Mint', emoji: '🌿', cal: 1 },
    { id: 's27', name: 'Tarragon', emoji: '🌿', cal: 2 }, { id: 's28', name: 'Star Anise', emoji: '⭐', cal: 7 },
  ]},
  { id: 'snacks', label: 'Snacks & Sweets', emoji: '🍫', color: '#f43f5e', items: [
    { id: 'sn1', name: 'Dark Chocolate', emoji: '🍫', cal: 170 }, { id: 'sn2', name: 'Milk Chocolate', emoji: '🍫', cal: 150 },
    { id: 'sn3', name: 'Potato Chips', emoji: '🥔', cal: 152 }, { id: 'sn4', name: 'Popcorn', emoji: '🍿', cal: 31 },
    { id: 'sn5', name: 'Crackers', emoji: '🟫', cal: 137 }, { id: 'sn6', name: 'Almonds', emoji: '🥜', cal: 164 },
    { id: 'sn7', name: 'Cashews', emoji: '🥜', cal: 157 }, { id: 'sn8', name: 'Walnuts', emoji: '🥜', cal: 185 },
    { id: 'sn9', name: 'Trail Mix', emoji: '🥜', cal: 131 }, { id: 'sn10', name: 'Granola Bar', emoji: '🍫', cal: 190 },
    { id: 'sn11', name: 'Donut', emoji: '🍩', cal: 253 }, { id: 'sn12', name: 'Cookie', emoji: '🍪', cal: 148 },
    { id: 'sn13', name: 'Brownie', emoji: '🍫', cal: 112 }, { id: 'sn14', name: 'Muffin', emoji: '🧁', cal: 340 },
    { id: 'sn15', name: 'Cupcake', emoji: '🧁', cal: 305 }, { id: 'sn16', name: 'Ice Cream', emoji: '🍦', cal: 137 },
    { id: 'sn17', name: 'Gummy Bears', emoji: '🐻', cal: 143 }, { id: 'sn18', name: 'Rice Cakes', emoji: '⬜', cal: 35 },
    { id: 'sn19', name: 'Protein Bar', emoji: '💪', cal: 200 }, { id: 'sn20', name: 'Hummus', emoji: '🥙', cal: 70 },
    { id: 'sn21', name: 'Nachos', emoji: '🧀', cal: 290 }, { id: 'sn22', name: 'Pretzels', emoji: '🥨', cal: 108 },
    { id: 'sn23', name: 'Peanuts', emoji: '🥜', cal: 166 }, { id: 'sn24', name: 'Sunflower Seeds', emoji: '🌻', cal: 165 },
  ]},
];